services:
  redis:
    image: redis:latest
    container_name: redis-docker
    expose:
      - ${REDIS_PORT}:${REDIS_PORT}
    attach: false
    logging:
      options:
        max-size: 5m

  spy:
    image: ghcr.io/wormhole-foundation/guardiand:latest
    platform: linux/amd64
    container_name: spy
    expose:
      - ${SPY_PORT}:${SPY_PORT}
    entrypoint: /guardiand
    command:
      - spy
      - --nodeKey
      - /node.key
      - --spyRPC
      - '[::]:${SPY_PORT}'
      - --env
      - mainnet
    attach: false
    profiles: ['wormhole']
    logging:
      options:
        max-size: 50m

  relayer:
    image: ghcr.io/catalystdao/generalised-relayer:latest
    build:
      context: .
      dockerfile: dockerfile.relayer
    volumes:
      - ./config.${NODE_ENV}.yaml:/usr/catalyst-relayer/config.${NODE_ENV}.yaml
      - ./.env:/usr/catalyst-relayer/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_HOST=redis
      - SPY_HOST=spy
    expose:
      - ${RELAYER_PORT}:${RELAYER_PORT}
    container_name: relayer
    restart: unless-stopped
    depends_on:
      - redis
    logging:
      options:
        max-size: 5g
